# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-27 15:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
