# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-10 20:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meter', '0002_sensor_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='logentry',
            options={'verbose_name': 'Sensor Log Entry', 'verbose_name_plural': 'Sensor Log Entries'},
        ),
        migrations.AlterModelOptions(
            name='sensor',
            options={'verbose_name': 'Sensor', 'verbose_name_plural': 'Sensors'},
        ),
    ]
